# Generated by Django 4.2.4 on 2023-08-11 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journey',
            options={'ordering': ['-departure_time']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('cargo', 'seat', 'journey')},
        ),
    ]
